name: Create Nuget Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
    - run: nuget pack JacobsApps.CleanArchitectureProjectTemplate.CSharp.nuspec -NoDefaultExcludes
    
    - name: Test nuget package with 'EmptyApi' project type
      run: ./test-nuget-package.sh EmptyApi Api
      shell: bash
    
    - name: Test nuget package with 'EmptyApi' project type
      run: ./test-nuget-package.sh FullApi Api
      shell: bash

    - name: Test nuget package with 'EmptyApi' project type
      run: ./test-nuget-package.sh EmptyBlazor Blazor
      shell: bash

    - name: Test nuget package with 'EmptyApi' project type
      run: ./test-nuget-package.sh FullBlazor Blazor
      shell: bash
      
    - name: Test nuget package with 'EmptyApi' project type
      run: ./test-nuget-package.sh EmptyWeb Web
      shell: bash      

    - name: Test nuget package with 'EmptyApi' project type
      run: ./test-nuget-package.sh FullWeb Web
      shell: bash 

    - name: Test nuget package with 'EmptyApi' project type
      run: ./test-nuget-package.sh All Full
      shell: bash 
      
    
      
